// AUTO-GENERATED by backend/app/GenerateTypes.hs
type TaskStatus = "TaskStatusPending" | "TaskStatusDesigning" | "TaskStatusImplementing" | "TaskStatusReviewing" | "TaskStatusQa" | "TaskStatusBlocked" | "TaskStatusCompleted" | "TaskStatusDiscarded" | "TaskStatusCancelled";

type WorkflowStep = "StepIntake" | "StepDesign" | "StepImplementation" | "StepSpecVerification" | "StepPmReview" | "StepQaReview" | "StepFixIteration" | "StepCommit" | "StepPreview" | "StepFinalize";

type AgentRole = "AgentRoleProjectManager" | "AgentRoleImplementer" | "AgentRoleQa" | "AgentRoleVerifier";

type AgentSessionStatus = "AgentSessionIdle" | "AgentSessionRunning" | "AgentSessionSucceeded" | "AgentSessionErrored";

type ArtifactKind = "ArtifactDesign" | "ArtifactDiff" | "ArtifactTestLog" | "ArtifactCommitLog" | "ArtifactPreviewLog" | "ArtifactPreviewPing" | "ArtifactAgentTranscript" | "ArtifactScreenshot" | "ArtifactVerificationEvidence" | "ArtifactVerifierReport";

type PreviewStatus = "PreviewOffline" | "PreviewLaunching" | "PreviewOnline" | "PreviewFailed";

type TaskSummary = ITaskSummary;

interface ITaskSummary {
  taskSummaryId: number;
  taskSummaryTitle: string;
  taskSummaryStatus: TaskStatus;
  taskSummaryRepoRoot: string;
  taskSummaryBranch: string;
  taskSummaryFeatureBranch: string | null;
  taskSummaryUpdatedAt: string;
  taskSummaryPreviewUrl: string | null;
  taskSummaryPreviewStatus: PreviewStatus;
  taskSummaryIsPaused: boolean;
  taskSummarySnoozeUntil: string | null;
}

type TaskRunInfo = ITaskRunInfo;

interface ITaskRunInfo {
  taskRunOrdinal: number;
  taskRunCurrentStep: WorkflowStep;
  taskRunPmSummary: string | null;
  taskRunCreatedAt: string;
  taskRunUpdatedAt: string;
}

type ArtifactDTO = IArtifactDTO;

interface IArtifactDTO {
  artifactId: number;
  artifactKind: ArtifactKind;
  artifactLabel: string;
  artifactBody: any | null;
  artifactPath: string | null;
  artifactCreatedAt: string;
}

type StatusEventDTO = IStatusEventDTO;

interface IStatusEventDTO {
  statusEventId: number | null;
  statusEventStep: WorkflowStep;
  statusEventMessage: string;
  statusEventCreatedAt: string;
  statusEventPayload: any | null;
}

type TaskDetail = ITaskDetail;

interface ITaskDetail {
  taskDetailSummary: TaskSummary;
  taskDetailRuns: TaskRunInfo[];
  taskDetailEvents: StatusEventDTO[];
  taskDetailArtifacts: ArtifactDTO[];
  taskDetailCriteria: AcceptanceCriterionDTO[];
  taskDetailTestCommand: string;
  taskDetailTestCommandOverride: string | null;
  taskDetailIsPaused: boolean;
  taskDetailSnoozeUntil: string | null;
  taskDetailEventNextCursor: number | null;
}

type TaskHistoryPage = ITaskHistoryPage;

interface ITaskHistoryPage {
  taskHistoryEvents: StatusEventDTO[];
  taskHistoryNextCursor: number | null;
}

type PromptTemplateDTO = IPromptTemplateDTO;

interface IPromptTemplateDTO {
  promptTemplateKey: string;
  promptTemplateDescription: string;
  promptTemplateContent: string;
  promptTemplateVersion: number;
  promptTemplateUpdatedAt: string;
  promptTemplateIsCustom: boolean;
}

type PromptRevisionDTO = IPromptRevisionDTO;

interface IPromptRevisionDTO {
  promptRevisionKey: string;
  promptRevisionVersion: number;
  promptRevisionEditor: string | null;
  promptRevisionContent: string;
  promptRevisionCreatedAt: string;
}

type AppSettingsDTO = IAppSettingsDTO;

interface IAppSettingsDTO {
  settingsDefaultRepoRoot: string;
  settingsDefaultBranch: string;
  settingsTestCommand: string;
  settingsPreviewCommand: string | null;
  settingsInactivityMinutes: number;
  settingsUpdatedAt: string;
}

type TaskCreateRequest = ITaskCreateRequest;

interface ITaskCreateRequest {
  taskReqTitle: string;
  taskReqDescription: string;
  taskReqRepoRoot: string | null;
  taskReqBranch: string | null;
}

type TaskUpdateStatusRequest = ITaskUpdateStatusRequest;

interface ITaskUpdateStatusRequest {
  taskStatus: TaskStatus;
}

type SettingsUpdateRequest = ISettingsUpdateRequest;

interface ISettingsUpdateRequest {
  settingsRepoRoot: string;
  settingsBranch: string;
  settingsUpdateTestCommand: string;
  settingsUpdatePreviewCommand: string | null;
  settingsUpdateInactivityMinutes: number;
}

type PromptUpdateRequest = IPromptUpdateRequest;

interface IPromptUpdateRequest {
  promptUpdateContent: string;
  promptUpdateDescription: string | null;
  promptUpdateVersion: number;
}

type PromptResetRequest = IPromptResetRequest;

interface IPromptResetRequest {
  promptResetKey: string;
}

type AgentMessageRequest = IAgentMessageRequest;

interface IAgentMessageRequest {
  agentMessage: string;
  agentMessageRole: AgentRole | null;
  agentMessageNextStep: WorkflowStep | null;
  agentMessageAutoResume: boolean | null;
}

type OrchestratorSnapshot = IOrchestratorSnapshot;

interface IOrchestratorSnapshot {
  snapshotActiveTasks: TaskSummary[];
  snapshotQueueDepth: number;
  snapshotWorkers: WorkerStatusDTO[];
  snapshotPausedTasks: number[];
  snapshotWorkerMetrics: WorkerMetricDTO[];
}