{-# LANGUAGE OverloadedStrings #-}
module Main where

import Data.Aeson.TypeScript.TH (TypeScript(..), formatTSDeclarations)
import Data.Proxy (Proxy(..))
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.IO as TLIO
import System.Environment (getArgs)

import Elm.Module (makeElmModule)

import App.Types

main :: IO ()
main = do
  args <- getArgs
  let (tsPath, elmPath) = case args of
        (tsFile : elmFile : _) -> (tsFile, elmFile)
        (tsFile : _) -> (tsFile, defaultElmPath)
        _ -> (defaultTsPath, defaultElmPath)
      decls = mconcat
        [ getTypeScriptDeclarations (Proxy :: Proxy TaskStatus)
        , getTypeScriptDeclarations (Proxy :: Proxy WorkflowStep)
        , getTypeScriptDeclarations (Proxy :: Proxy AgentRole)
        , getTypeScriptDeclarations (Proxy :: Proxy AgentSessionStatus)
        , getTypeScriptDeclarations (Proxy :: Proxy ArtifactKind)
        , getTypeScriptDeclarations (Proxy :: Proxy PreviewStatus)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskSummary)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskRunInfo)
        , getTypeScriptDeclarations (Proxy :: Proxy ArtifactDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy StatusEventDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskDetail)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskHistoryPage)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptTemplateDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptRevisionDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy AppSettingsDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskCreateRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskUpdateStatusRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy SettingsUpdateRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptUpdateRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptResetRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy AgentMessageRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy OrchestratorSnapshot)
        ]
      tsHeader = TL.pack "// AUTO-GENERATED by backend/app/GenerateTypes.hs\n"
      elmModule =
        let raw = TL.pack (makeElmModule "Generated.Api" elmDefinitions)
            withFixes = TL.replace "exposing(..)" "exposing (..)" raw
            withTime = TL.replace "import Json.Encode exposing (Value)\n" "import Json.Encode exposing (Value)\nimport Iso8601\nimport Time exposing (Posix)\n" withFixes
            withTestDecoder = TL.replace
              "jsonDecTaskTestCommandUpdateRequest =\n   Json.Decode.succeed (\\ptaskTestCommand -> {taskTestCommand = ptaskTestCommand}) |> custom (Json.Decode.string)\n"
              "jsonDecTaskTestCommandUpdateRequest =\n   Json.Decode.succeed (\\ptaskTestCommand -> {taskTestCommand = ptaskTestCommand})\n   |> fnullable \"taskTestCommand\" (Json.Decode.string)\n"
              withTime
            withRetryDecoder = TL.replace
              "jsonDecTaskRetryRequest =\n   Json.Decode.succeed (\\ptaskRetryInstructions -> {taskRetryInstructions = ptaskRetryInstructions}) |> custom (Json.Decode.string)\n"
              "jsonDecTaskRetryRequest =\n   Json.Decode.succeed (\\ptaskRetryInstructions -> {taskRetryInstructions = ptaskRetryInstructions})\n   |> fnullable \"taskRetryInstructions\" (Json.Decode.string)\n"
              withTestDecoder
            withRedirectDecoder = TL.replace
              "jsonDecTaskRedirectRequest =\n   Json.Decode.succeed (\\ptaskRedirectTargetTaskId -> {taskRedirectTargetTaskId = ptaskRedirectTargetTaskId}) |> custom (Json.Decode.int)\n"
              "jsonDecTaskRedirectRequest =\n   Json.Decode.succeed (\\ptaskRedirectTargetTaskId -> {taskRedirectTargetTaskId = ptaskRedirectTargetTaskId})\n   |> required \"taskRedirectTargetTaskId\" (Json.Decode.int)\n"
              withRetryDecoder
            helperBlock = TL.pack "\njsonDecPosix : Json.Decode.Decoder Posix\njsonDecPosix =\n    Json.Decode.string\n        |> Json.Decode.andThen\n            (\\str ->\n                case Iso8601.toTime str of\n                    Ok posix ->\n                        Json.Decode.succeed posix\n\n                    Err _ ->\n                        Json.Decode.fail \"Invalid ISO8601 timestamp\"\n            )\n\njsonEncPosix : Posix -> Value\njsonEncPosix posix =\n    Json.Encode.string (Iso8601.fromTime posix)\n\njsonDecValue : Json.Decode.Decoder Value\njsonDecValue =\n    Json.Decode.value\n\njsonEncValue : Value -> Value\njsonEncValue value =\n    value\n\n"
        in TL.replace "import Set exposing (Set)\n\n" ("import Set exposing (Set)\n\n" <> helperBlock) withRedirectDecoder
  TLIO.writeFile tsPath (tsHeader <> TL.pack (formatTSDeclarations decls))
  TLIO.writeFile elmPath (TL.pack "-- AUTO-GENERATED by backend/app/GenerateTypes.hs\n\n" <> elmModule)
  putStrLn $ "Type declarations written to " <> tsPath
  putStrLn $ "Elm module written to " <> elmPath
  where
    defaultTsPath = "frontend/src/types/app.d.ts"
    defaultElmPath = "frontend/src/Generated/Api.elm"
