{-# LANGUAGE OverloadedStrings #-}
module Main where

import App.Types
import Data.Aeson.TypeScript.TH (TypeScript(..), formatTSDeclarations)
import Data.Proxy (Proxy(..))
import qualified Data.Text.Lazy as TL
import qualified Data.Text.Lazy.IO as TLIO
import System.Environment (getArgs)

main :: IO ()
main = do
  args <- getArgs
  let output = case args of
        (path:_) -> path
        _ -> "../frontend/src/types/app.d.ts"
      decls = mconcat
        [ getTypeScriptDeclarations (Proxy :: Proxy TaskStatus)
        , getTypeScriptDeclarations (Proxy :: Proxy WorkflowStep)
        , getTypeScriptDeclarations (Proxy :: Proxy AgentRole)
        , getTypeScriptDeclarations (Proxy :: Proxy AgentSessionStatus)
        , getTypeScriptDeclarations (Proxy :: Proxy ArtifactKind)
        , getTypeScriptDeclarations (Proxy :: Proxy PreviewStatus)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskSummary)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskRunInfo)
        , getTypeScriptDeclarations (Proxy :: Proxy ArtifactDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy StatusEventDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskDetail)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptTemplateDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptRevisionDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy AppSettingsDTO)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskCreateRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy TaskUpdateStatusRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy SettingsUpdateRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptUpdateRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy PromptResetRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy AgentMessageRequest)
        , getTypeScriptDeclarations (Proxy :: Proxy OrchestratorSnapshot)
        ]
      header = TL.pack "// AUTO-GENERATED by backend/app/GenerateTypes.hs\n"
  TLIO.writeFile output (header <> TL.pack (formatTSDeclarations decls))
  putStrLn $ "Type declarations written to " <> output
